"""
Native pgfplots (TikZ) figure: cross-game aggregate learning curves, one mean
line per condition.

Because the target games live on very different return scales (Breakout ~40,
Up'n'Down ~7000), raw returns cannot be averaged across games -- Up'n'Down would
dominate. We therefore convert each game's curve to a human-normalized score
(HNS = (score - random) / (human - random)) using the paper's reference values,
then average the per-game (seed-mean) HNS curves across the four target games at
each evaluation point. Freeway is excluded: the base model never leaves the floor
there, so transfer is untestable (and only scratch + freeze-L0 were run).

Bands are +/- std ACROSS the four games (cross-game consistency of the pattern),
not across seeds.

Data: wandb_export/eval_epoch_long.csv  (per-epoch score, all games/conds/seeds).

Outputs:
  results/figures/aggregate_curves.tex
  results/figures/aggregate_curves_standalone.tex

Usage:
  python scripts/plot_aggregate_curves_tikz.py
"""

import argparse
import csv
import statistics as st
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "results" / "figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)
EVAL_CSV = ROOT / "wandb_export" / "eval_epoch_long.csv"

# (random, human) Atari-100k reference scores, from the paper's 2x2 table.
REF = {
    "breakout":     (1.7, 30.5),
    "demon_attack": (152.0, 1971.0),
    "ms_pacman":    (307.0, 6952.0),
    "up_n_down":    (533.0, 11693.0),
}
GAMES = list(REF)

# condition -> (display name, colour, line width pt, is-anchor)
STYLE = {
    "scratch":     ("from-scratch", "black",  1.6, True),
    "warmstart":   ("warmstart",    "teal",   0.9, False),
    "freeze-L0":   ("freeze-L0",    "blue",   0.9, False),
    "freeze-L01":  ("freeze-L01",   "olive",  0.9, False),
    "freeze-L012": ("freeze-L012",  "orange", 0.9, False),
    "freeze-enc":  ("freeze-enc",   "violet", 0.9, False),
    "freeze-all":  ("freeze-all",   "red",    1.6, True),
}
ORDER = ["scratch", "warmstart", "freeze-L0", "freeze-L01",
         "freeze-L012", "freeze-enc", "freeze-all"]
XS = [10 * i for i in range(1, 11)]   # env steps in 10^3


def hns(game, v):
    rnd, hum = REF[game]
    return (v - rnd) / (hum - rnd)


def load(seed_stat="median"):
    """condition -> (centre[10], std_across_games[10], n_games).

    The per-game seed aggregate defaults to the MEDIAN. With the mean, the single
    ~37k Up'n'Down freeze-L0 seed dragged that condition's aggregate curve ABOVE
    from-scratch, which contradicts the paper text and the per-game tables; the
    median is robust to it and reproduces the reported ordering. `seed_stat="mean"`
    reproduces the old (misleading) curve for comparison only.
    """
    agg = {"median": st.median, "mean": st.mean}[seed_stat]
    rows = [r for r in csv.DictReader(open(EVAL_CSV, encoding="utf-8"))
            if r["metric"] == "score" and r["game"] in REF]
    # game -> cond -> epoch -> [seed values]
    D = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for r in rows:
        D[r["game"]][r["condition"]][int(r["epoch_idx"])].append(float(r["value"]))
    out = {}
    for c in ORDER:
        centre, std, ng = [], [], 0
        for e in range(10):
            per_game = []
            for g in GAMES:
                vals = D[g][c].get(e)
                if vals:
                    per_game.append(hns(g, agg(vals)))
            ng = max(ng, len(per_game))
            centre.append(st.mean(per_game) if per_game else 0.0)
            std.append(st.pstdev(per_game) if len(per_game) > 1 else 0.0)
        out[c] = (centre, std, ng)
    return out


def coords(xs, ys):
    return " ".join(f"({x},{y:.4f})" for x, y in zip(xs, ys))


def emit_figure(data, bands, seed_stat="median"):
    L = []
    ap = L.append
    ap("% Generated by scripts/plot_aggregate_curves_tikz.py")
    ap("\\begin{figure}[t]")
    ap("    \\centering")
    ap("    \\begin{tikzpicture}")
    ap("    \\begin{axis}[")
    ap("        width=0.92\\linewidth, height=6.2cm,")
    ap("        xlabel={Environment steps ($\\times 10^3$)},")
    ap("        ylabel={Human-normalized score (%s over seeds, mean over 4 games)},"
       % seed_stat)
    ap("        xmin=10, xmax=100, ymin=0,")
    ap("        legend pos=north west, legend columns=2, legend cell align=left,")
    ap("        legend style={font=\\scriptsize, draw=none, fill=none, "
       "/tikz/every even column/.append style={column sep=6pt}},")
    ap("        tick label style={font=\\footnotesize},")
    ap("        label style={font=\\small},")
    ap("        grid=major, grid style={black!8},")
    ap("        clip mode=individual,")
    ap("    ]")

    # optional translucent bands first
    for c in ORDER:
        if c not in bands:
            continue
        name, col, lw, anchor = STYLE[c]
        m, s, _ = data[c]
        hi = [a + b for a, b in zip(m, s)]
        lo = [max(0.0, a - b) for a, b in zip(m, s)]
        ap(f"        \\addplot[draw=none, forget plot, name path={c}hi] "
           f"coordinates {{{coords(XS, hi)}}};")
        ap(f"        \\addplot[draw=none, forget plot, name path={c}lo] "
           f"coordinates {{{coords(XS, lo)}}};")
        ap(f"        \\addplot[{col}!10, forget plot] "
           f"fill between[of={c}hi and {c}lo];")

    # mean lines
    for c in ORDER:
        name, col, lw, anchor = STYLE[c]
        m, s, ng = data[c]
        ap(f"        % {c} (n_games={ng})")
        ap(f"        \\addplot[{col}, line width={lw}pt] "
           f"coordinates {{{coords(XS, m)}}};")
        lbl = f"\\textbf{{{name}}}" if anchor else name
        ap(f"        \\addlegendentry{{{lbl}}}")

    ap("    \\end{axis}")
    ap("    \\end{tikzpicture}")
    ap("    \\caption{Cross-game aggregate learning curves. Each game's eval "
       "return is human-normalized (HNS $=$ (score $-$ random)/(human $-$ random)); "
       "per-game curves take the \\textbf{%s} across seeds, and the four target-game "
       "curves are then averaged (Breakout, Demon Attack, Ms Pac-Man, Up'n'Down; "
       "Freeway excluded, not learnable from scratch). The seed-wise %s is used "
       "because the mean is dominated by a single $\\sim$37k Up'n'Down "
       "\\textsc{freeze-L0} seed, which places that condition above from-scratch and "
       "contradicts the per-game tables. The two fully-frozen-codebook regimes "
       "(\\textbf{freeze-L012}, \\textbf{freeze-all}) sit lowest; \\textbf{freeze-all} "
       "is consistently last. Bands (when shown) are $\\pm$ std across the four "
       "games.}" % (seed_stat, seed_stat))
    ap("    \\label{fig:aggregate_curves}")
    ap("\\end{figure}")
    return "\n".join(L) + "\n"


STANDALONE_HEAD = r"""\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{fillbetween}
\usepackage[margin=0.7in]{geometry}
\begin{document}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bands", nargs="*", default=["scratch", "freeze-all"],
                    choices=ORDER, help="conditions to draw std-across-games bands for")
    ap.add_argument("--seed-stat", choices=["median", "mean"], default="median",
                    help="per-game aggregate across seeds (default median; 'mean' "
                         "reproduces the outlier-dominated curve for comparison)")
    args = ap.parse_args()
    data = load(args.seed_stat)
    fig = emit_figure(data, set(args.bands), args.seed_stat)
    (OUT_DIR / "aggregate_curves.tex").write_text(fig, encoding="utf-8")
    (OUT_DIR / "aggregate_curves_standalone.tex").write_text(
        STANDALONE_HEAD + fig + "\\end{document}\n", encoding="utf-8")
    print(f"[ok] {OUT_DIR/'aggregate_curves.tex'} (bands={args.bands})")
    print(f"[ok] {OUT_DIR/'aggregate_curves_standalone.tex'}")


if __name__ == "__main__":
    main()
