"""
Emit a native pgfplots (TikZ) learning-curve figure for Breakout: one condition
drawn as a bold solid mean line, the others as translucent mean +/- std bands in
distinct colours, all on shared axes.

Data:
  wandb_export/eval_epoch_long.csv  (per-epoch eval score, ALL seeds, all conditions)

This is the SAME seed set the paper tables aggregate (Breakout: scratch n=6,
warmstart/freeze-L01/freeze-enc/freeze-all n=9, freeze-L0/freeze-L012 n=10);
reconstructing the last-5 mean from it reproduces Table~\ref{tab:results_main}.
Do NOT use results/transfer_pong_to_breakout/*.csv here -- those hold only the
3-seed checkpoint subset and disagree with the tables (e.g. freeze-L0 44.6 vs 33.7).

The x-axis is environment steps (10 eval points over the 10^5-step budget, i.e.
10k, 20k, ..., 100k); the export's `step` column is exactly 10000..100000.

Outputs:
  results/figures/breakout_curves.tex          (the \begin{figure}... block to \input)
  results/figures/breakout_curves_standalone.tex (compile check wrapper)

Usage:
  python scripts/plot_breakout_curves_tikz.py --highlight scratch
"""

import argparse
import csv
import statistics as st
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "results" / "figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)
EVAL_CSV = ROOT / "wandb_export" / "eval_epoch_long.csv"
GAME = "breakout"

# display name, pgf colour (xcolor), for each condition key
STYLE = {
    "scratch":     ("from-scratch", "black"),
    "warmstart":   ("warmstart",    "teal"),
    "freeze-L0":   ("freeze-L0",    "blue"),
    "freeze-L01":  ("freeze-L01",   "olive"),
    "freeze-L012": ("freeze-L012",  "orange"),
    "freeze-enc":  ("freeze-enc",   "violet"),
    "freeze-all":  ("freeze-all",   "red"),
}
ORDER = ["scratch", "warmstart", "freeze-L0", "freeze-L01",
         "freeze-L012", "freeze-enc", "freeze-all"]
XS = [10 * i for i in range(1, 11)]   # env steps in 10^3


def load():
    """Aggregate per-epoch eval score over all seeds, per condition.

    Returns {condition: (mean[10], std[10], n_seeds)}. Aggregation is per
    epoch_idx over whatever seeds reported that point (handles ragged seeds);
    std is the population std across seeds, matching the tables.
    """
    rows = [r for r in csv.DictReader(open(EVAL_CSV, encoding="utf-8"))
            if r["game"] == GAME and r["metric"] == "score"]
    # condition -> epoch_idx -> list of per-seed values
    by = defaultdict(lambda: defaultdict(list))
    seeds = defaultdict(set)
    for r in rows:
        c = r["condition"]
        by[c][int(r["epoch_idx"])].append(float(r["value"]))
        seeds[c].add(r["seed"])
    out = {}
    for c, ev in by.items():
        idxs = sorted(ev)[:10]
        mean = [st.mean(ev[i]) for i in idxs]
        std = [st.pstdev(ev[i]) if len(ev[i]) > 1 else 0.0 for i in idxs]
        out[c] = (mean, std, len(seeds[c]))
    return out


def coords(xs, ys):
    return " ".join(f"({x},{y:.2f})" for x, y in zip(xs, ys))


def emit_figure(data, highlight, bands):
    lines = []
    ap = lines.append
    ap("% Generated by scripts/plot_breakout_curves_tikz.py")
    ap("\\begin{figure}[t]")
    ap("    \\centering")
    ap("    \\begin{tikzpicture}")
    ap("    \\begin{axis}[")
    ap("        width=0.92\\linewidth, height=6cm,")
    ap("        xlabel={Environment steps ($\\times 10^3$)},")
    ap("        ylabel={Breakout episode return},")
    ap("        xmin=10, xmax=100, ymin=0,")
    ap("        legend pos=north west, legend cell align=left,")
    ap("        legend style={font=\\scriptsize, draw=none, fill=none},")
    ap("        tick label style={font=\\footnotesize},")
    ap("        label style={font=\\small},")
    ap("        grid=major, grid style={black!8},")
    ap("        clip mode=individual,")
    ap("    ]")

    # bands first (so the highlighted line draws on top)
    for c in ORDER:
        if c == highlight or c not in bands:
            continue
        name, col = STYLE[c]
        m, s, n = data[c]
        hi = [a + b for a, b in zip(m, s)]
        lo = [max(0.0, a - b) for a, b in zip(m, s)]
        ap(f"        % --- {c} band (n={n}) ---")
        ap(f"        \\addplot[draw=none, forget plot, name path={c}hi] "
           f"coordinates {{{coords(XS, hi)}}};")
        ap(f"        \\addplot[draw=none, forget plot, name path={c}lo] "
           f"coordinates {{{coords(XS, lo)}}};")
        ap(f"        \\addplot[{col}!12, forget plot] "
           f"fill between[of={c}hi and {c}lo];")
        ap(f"        \\addplot[{col}!75, line width=0.7pt] "
           f"coordinates {{{coords(XS, m)}}};")
        ap(f"        \\addlegendentry{{{name}}}")

    # highlighted condition: bold solid mean line on top
    name, col = STYLE[highlight]
    m, s, n = data[highlight]
    ap(f"        % --- {highlight} highlighted mean (n={n}) ---")
    ap(f"        \\addplot[{col}, line width=1.6pt] "
       f"coordinates {{{coords(XS, m)}}};")
    ap(f"        \\addlegendentry{{\\textbf{{{name}}}}}")

    ap("    \\end{axis}")
    ap("    \\end{tikzpicture}")
    # accurate per-condition seed counts in the caption
    shown = [highlight] + [c for c in ORDER if c in bands and c != highlight]
    ncount = ", ".join(f"{STYLE[c][0]} $n{{=}}{data[c][2]}$" for c in shown)
    ap("    \\caption{Breakout evaluation return over training (Atari~100k, 10 "
       "evaluation points; environment steps $10^4$--$10^5$). The \\textbf{" + name
       + "} condition is drawn as a bold solid mean line; the remaining conditions "
       "are shown as translucent mean\\,$\\pm$\\,std bands over seeds. Seed counts: "
       + ncount + ". Aggregated per evaluation point over all seeds from "
       "\\texttt{wandb\\_export/eval\\_epoch\\_long.csv}, the same seed set as "
       "Table~\\ref{tab:results_main}.}")
    ap("    \\label{fig:breakout_curves}")
    ap("\\end{figure}")
    return "\n".join(lines) + "\n"


STANDALONE_HEAD = r"""\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{fillbetween}
\usepackage[margin=0.7in]{geometry}
\begin{document}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--highlight", default="scratch", choices=ORDER)
    ap.add_argument("--bands", nargs="+", default=["freeze-L0", "freeze-L01", "freeze-L012"],
                    choices=ORDER, help="conditions to draw as mean+/-std bands")
    args = ap.parse_args()

    data = load()
    fig = emit_figure(data, args.highlight, args.bands)

    (OUT_DIR / "breakout_curves.tex").write_text(fig, encoding="utf-8")
    (OUT_DIR / "breakout_curves_standalone.tex").write_text(
        STANDALONE_HEAD + fig + "\\end{document}\n", encoding="utf-8")
    print(f"[ok] {OUT_DIR/'breakout_curves.tex'} (highlight={args.highlight})")
    print(f"[ok] {OUT_DIR/'breakout_curves_standalone.tex'}")


if __name__ == "__main__":
    main()
